# Generated by Django 5.1.7 on 2025-04-20 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topicName", models.CharField(max_length=200)),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                ("interactionCount", models.IntegerField(default=0)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["-creationDate"],
                "indexes": [
                    models.Index(
                        fields=["creationDate"], name="topics_creatio_57db19_idx"
                    )
                ],
            },
        ),
    ]
