# Generated by Django 5.1.7 on 2025-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
