# Generated by Django 5.1.7 on 2025-03-30 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0002_initial"),
        ("graphs", "0002_initial"),
        ("topics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-interactionCount", "-creationDate"]},
        ),
        migrations.AddField(
            model_name="topic",
            name="forum",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_forum",
                to="forums.forum",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="graph",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graphs.graph",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="interactionCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["interactionCount"], name="topics_interac_5dfe95_idx"
            ),
        ),
    ]
