# Generated by Django 5.1.7 on 2025-03-30 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_alter_topic_options_topic_forum_topic_graph_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-creationDate"]},
        ),
        migrations.RemoveIndex(
            model_name="topic",
            name="topics_interac_5dfe95_idx",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="graph",
        ),
    ]
