# Generated by Django 5.1.7 on 2025-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="topicName",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
