version: '3.8'

services:
  frontend:
    build: ./connecthedots/frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./connecthedots/backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=connecthedots.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/connecthedots
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=connecthedots
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 