version: '3.8'

services:
  frontend:
    build: ./connecthedots/frontend
    ports:
      - "3000:80"        # Host port 3000 -> container port 80 (allowed by EC2 inbound)
    env_file:
      - .env
    depends_on:
      - backend
    mem_limit: 512M
    restart: unless-stopped

  backend:
    build: ./connecthedots/backend
    ports:
      - "8000:8000"     # Host port 8000 -> container port 8000 (allowed by EC2 inbound)
    env_file:
      - .env
    depends_on:
      - db
    mem_limit: 512M
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 256M
    restart: unless-stopped

volumes:
  postgres_data: