# Generated by Django 5.1.7 on 2025-03-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forums", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forums",
                to="topics.topic",
            ),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["created_at"], name="forums_created_fde5c4_idx"),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["topic"], name="forums_topic_i_aaa24b_idx"),
        ),
    ]
