# Generated by Django 5.1.7 on 2025-04-20 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTopics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted", models.BooleanField(default=False)),
                ("created", models.BooleanField(default=False)),
                ("addedNode", models.BooleanField(default=False)),
                ("actionDate", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_topics",
                        to="topics.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Topic",
                "verbose_name_plural": "User Topics",
                "db_table": "user_topics",
                "unique_together": {("user", "topic")},
            },
        ),
    ]
