# Generated by Django 5.1.7 on 2025-04-03 18:53

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertopics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertopics',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertopics',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertopics',
            name='addedNode',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='usertopics',
            old_name='creationDate',
            new_name='actionDate',
        ),
        migrations.AlterUniqueTogether(
            name='usertopics',
            unique_together={('user', 'topic')},
        ),
    ]
