# Generated by Django 5.1.7 on 2025-03-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="topics.topic",
            ),
        ),
    ]
