# Generated by Django 5.1.7 on 2025-05-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        ("wikis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to="wikis.wiki",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "db_table": "nodes",
                "indexes": [
                    models.Index(
                        fields=["created_by_user"], name="nodes_created_3b3dd1_idx"
                    ),
                    models.Index(fields=["qid"], name="nodes_qid_id_dbf578_idx"),
                ],
            },
        ),
    ]
