# Generated by Django 5.1.7 on 2025-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "nodes",
            },
        ),
    ]
