# Generated by Django 5.1.7 on 2025-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="position_x",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="node",
            name="position_y",
            field=models.FloatField(default=0),
        ),
    ]
