# Generated by Django 5.1.7 on 2025-03-20 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("graphs", "0002_initial"),
        ("nodes", "0001_initial"),
        ("topics", "0001_initial"),
        ("wikis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_nodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="graphs.graph",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="qid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nodes",
                to="wikis.wiki",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="topics.topic",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["topic"], name="nodes_topic_i_686d3f_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["created_by_user"], name="nodes_created_3b3dd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["graph"], name="nodes_graph_i_268054_idx"),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["qid"], name="nodes_qid_id_dbf578_idx"),
        ),
    ]
