# Generated by Django 5.1.7 on 2025-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("relationName", models.CharField(max_length=255)),
                (
                    "relationDirection",
                    models.CharField(
                        choices=[
                            ("UNDIRECTED", "Undirected"),
                            ("FIRST_TO_SECOND", "First to Second"),
                            ("SECOND_TO_FIRST", "Second to First"),
                        ],
                        default="UNDIRECTED",
                        max_length=20,
                    ),
                ),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "connections",
            },
        ),
    ]
