# Generated by Django 5.1.7 on 2025-04-20 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("relationName", models.CharField(max_length=255)),
                (
                    "relationDirection",
                    models.CharField(
                        choices=[
                            ("UNDIRECTED", "Undirected"),
                            ("FIRST_TO_SECOND", "First to Second"),
                            ("SECOND_TO_FIRST", "Second to First"),
                        ],
                        default="UNDIRECTED",
                        max_length=20,
                    ),
                ),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firstNodeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_node_connections",
                        to="nodes.node",
                    ),
                ),
                (
                    "secondNodeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_node_connections",
                        to="nodes.node",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "db_table": "connections",
                "indexes": [
                    models.Index(
                        fields=["createdBy"], name="connections_created_b05425_idx"
                    )
                ],
            },
        ),
    ]
