# Generated by Django 5.1.7 on 2025-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wiki",
            fields=[
                (
                    "qID",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wiki",
                "verbose_name_plural": "Wikis",
                "db_table": "wikis",
                "indexes": [models.Index(fields=["qID"], name="wikis_qID_eece85_idx")],
            },
        ),
    ]
