# Generated by Django 5.1.7 on 2025-03-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_nodes",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "db_table": "usernodes",
                "ordering": ["-creationDate"],
            },
        ),
    ]
